# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
            exclude: '^cfn/.*'
        -   id: check-json
        -   id: check-added-large-files
  -   repo: https://github.com/markdownlint/markdownlint
      rev: v0.15.0
      hooks:
        -   id: markdownlint_docker
  -   repo: https://github.com/fsfe/reuse-tool
      rev: v6.2.0
      hooks:
        -   id: reuse
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: v4.10.0
      hooks:
        -   id: commitizen
  -   repo: https://github.com/aws-cloudformation/cfn-lint
      rev: v1.43.1
      hooks:
        - id: cfn-lint
          files: '^cfn/.*'
  -   repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.11.0.1
      hooks:
        - id: shellcheck
          args:
            - -x
