# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

template-file-path: cfn/iac.yaml
parameters:
  AutomationAccountId: "992382418145"
  AwsOrgOUIdProjects: ou-lp71-146074dn
  OpenTofuRemoteBackendBucketName: dominik-wombacher-iac-opentofu
  OpenTofuRemoteBackendDDBTableName: dominik-wombacher-iac-opentofu
  OpenTofuRemoteBackendKMSKeyAlias: backend-encryption
  GitHubOrg: wombelix
  GitHubRepoName: infra-aws-org
tags:
  Purpose: IaC
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
