# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

template-file-path: cfn/budget.yaml
parameters:
  AlertSnsTopicArn: arn:aws:sns:eu-central-1:992382651568:Notifications
tags:
  Purpose: AWSOrg
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
