# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

template-file-path: cfn/scp.yaml
parameters:
  OrganizationRootId: r-lp71
tags:
  Purpose: AWSOrg
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
